### ISSUE TITLE
Using AzureDataBus with the NServiceBus.Host results in AggregateException when bus is created

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.AzureBlobStorageDataBus#6] opened 2015-09-18 16:18 UTC
Using AzureDataBus with the NServiceBus.Host results in `AggregateException` when bus is created.

Using the `FileShareDataBus` works fine, also using the `AzureDataBus` when self-hosting is not an issue.

Customer mentioned that `AzureDataBus` with `NServiceBus.Host` worked in v4.x so it is broken by v5.

## Fix

The fix is to add the correct assembly redirects to a configuration file for the NServiceBus.Host.exe

See the following sample:

- https://github.com/ramonsmits/docs.particular.net/tree/desk/13300/samples/azure/blob-storage-databus/Version_5

This copies `app.config` to `NServiceBus.Host.exe.config`.

## Exception

```
2015-09-18 17:57:32.198 ERROR NServiceBus Startup task failed to complete.
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at NServiceBus.Features.DataBus.IDataBusInitializer.OnStart() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\DataBus\DataBus.cs:line 42
   at NServiceBus.Features.FeatureActivator.StartFeatures(IBuilder builder) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Features\FeatureActivator.cs:line 143
   at NServiceBus.Unicast.UnicastBus.<Start>b__9(IWantToRunWhenBusStartsAndStops toRun) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\UnicastBus.cs:line 684
   at System.Threading.Tasks.Parallel.<>c__DisplayClass9`1.<ForWorker>b__11()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass0.<ExecuteSelfReplicating>b__1(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at NServiceBus.Unicast.UnicastBus.<>c__DisplayClass11`1.<ProcessStartupItems>b__10() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\UnicastBus.cs:line 927
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at NServiceBus.Features.DataBus.IDataBusInitializer.OnStart() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\DataBus\DataBus.cs:line 42
   at NServiceBus.Features.FeatureActivator.StartFeatures(IBuilder builder) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Features\FeatureActivator.cs:line 143
   at NServiceBus.Unicast.UnicastBus.<Start>b__9(IWantToRunWhenBusStartsAndStops toRun) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\UnicastBus.cs:line 684
   at System.Threading.Tasks.Parallel.<>c__DisplayClass9`1.<ForWorker>b__11()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass0.<ExecuteSelfReplicating>b__1(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at NServiceBus.Unicast.UnicastBus.<>c__DisplayClass11`1.<ProcessStartupItems>b__10() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\UnicastBus.cs:line 927
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at NServiceBus.Features.DataBus.IDataBusInitializer.OnStart() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\DataBus\DataBus.cs:line 42
   at NServiceBus.Features.FeatureActivator.StartFeatures(IBuilder builder) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Features\FeatureActivator.cs:line 143
   at NServiceBus.Unicast.UnicastBus.<Start>b__9(IWantToRunWhenBusStartsAndStops toRun) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\UnicastBus.cs:line 684
   at System.Threading.Tasks.Parallel.<>c__DisplayClass9`1.<ForWorker>b__11()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass0.<ExecuteSelfReplicating>b__1(Object )<---
<---
```

**Comment by yvesgoeleven** [comment] 2015-09-18 18:04
Just tried your repro, but it works fine on my machine...

**Comment by yvesgoeleven** [comment] 2015-09-22 14:33
We've been able to reproduce this issue using the regular nservicebus host, couldn't reproduce it using self host. It looks like the AzureDataBusPersistence feature is not in the in memory list of features to activate when using the regular nservicebus host, so no databus is loaded. We are now trying to figure out why the type is not in the feature list

**Comment by ramonsmits** [comment] 2015-09-22 15:01
@yvesgoeleven Good work on finding the issue. I cannot remember that I saw a typeload exception. Are those catched without logging by us?

**Comment by yvesgoeleven** [comment] 2015-09-22 15:02
No they are not logged

**Comment by SeanFeldman** [comment] 2015-09-22 15:14
@ramonsmits this is an issue with `AssemblyScanner` - it doesn't log any information. Since exception is swallowed, that information never bubbles up :(

**Comment by SeanFeldman** [comment] 2015-09-22 19:25
Question I have is how we should handle assemblies that require dependencies with asm binding redirects? `AssemblyScanner`should not block an assembly because it's failing, nor should we replicate binding redirects in two configuration files (one for host and one for endpoint). 

I thought of logging that failure, but then it would be confusing to users - they'll see the error and at the same tie binding redirects in endpoint`s config file.

/cc @andreasohlund

**Comment by andreasohlund** [comment] 2015-09-23 06:49
The host is only scanning to find the impl of `IConfigureThisEndpoint`. I think the fix is to not pass any assemblies to the appdomain if there is > 0 scanning failures in the host. This will force the appdomain to rescan and if there are appropriate redirects be able to load the missing dep?

**Comment by ramonsmits** [comment] 2015-09-23 09:44
I've update the sample with a working version including the assembly redirects for the host. I also updated the issue description where I changed the 'Sample' section to 'Fix'.

**Comment by SeanFeldman** [comment] 2015-09-23 18:28
@andreasohlund :+1: to what you suggested.

@ramonsmits don't think we need to change how samples are working. What we need is to fix nsb host (and azure host for that purpose).

**Comment by SeanFeldman** [comment] 2015-09-24 18:27
Closing in favour of https://github.com/Particular/NServiceBus.Host/issues/42

**Closed by SeanFeldman** 2015-09-24 18:27 UTC
Labels: Type: Bug

**Comment by ramonsmits** [comment] 2015-09-24 19:45
@SeanFeldman I agree that the Host should fail on assembly scanning load exceptions as that that we can pro actively report such errors.

Assembly redirects are still required in the NServiceBus.Host.exe.config.

I updated the sample as the assembly redirects are required for it to operate and I communicated this to the customer to solve their issue.
